version: '3.8'
services:
  backend:
    build:
      context: .
    ports:
      - "8081:8081"
    networks:
      - dms-network

  frontend:
    build:
      context: ./web-ui
    ports:
      - "8080:80"
    networks:
      - dms-network
    depends_on:
      - backend

networks:
  dms-network:
    driver: bridge
