version: '3.8'
services:
  backend:
    build:
      context: .
    ports:
      - "8081:8081"
    networks:
      - dms-network
    depends_on:
      - rabbitmq
      - postgres

  frontend:
    build:
      context: ./web-ui
    ports:
      - "80:80"
    networks:
      - dms-network
    depends_on:
      - backend

  postgres:
    image: postgres:14
    container_name: documentDB
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: documents_db
    ports:
      - "5432:5432"
    networks:
      - dms-network

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "15672:15672"  # For RabbitMQ management UI
      - "5672:5672"    # For client connections to RabbitMQ
    networks:
      - dms-network

networks:
  dms-network:
    driver: bridge
