version: '3.8'
services:
  backend:
    build:
      context: .
    ports:
      - "8081:8081"
    networks:
      - dms-network

  frontend:
    build:
      context: ./web-ui
    ports:
      - "80:80"
    networks:
      - dms-network
    depends_on:
      - backend

  postgres:
    image: postgres:14
    container_name: documentDB
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: documents_db
    ports:
      - "5432:5432"
    networks:
      - dms-network

networks:
  dms-network:
    driver: bridge
