version: '3.8'
services:
  backend:
    build:
      context: .
    ports:
      - "8081:8081"
    networks:
      - dms-network
    depends_on:
      - rabbitmq
      - postgres
      - minio

  frontend:
    build:
      context: ./web-ui
    ports:
      - "80:80"
    networks:
      - dms-network
    depends_on:
      - backend

  postgres:
    image: postgres:14
    container_name: documentDB
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: documents_db
    ports:
      - "5432:5432"
    networks:
      - dms-network

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "15672:15672"  # For RabbitMQ management UI
      - "5672:5672"    # For client connections to RabbitMQ
    networks:
      - dms-network

  minio:
    image: minio/minio:latest
    container_name: minio
    environment:
      MINIO_ROOT_USER: "minioaccesskey"  # MinIO Access Key
      MINIO_ROOT_PASSWORD: "miniosecretkey"  # MinIO Secret Key
    ports:
      - "9000:9000"  # MinIO API port
      - "9090:9090"  # MinIO Console port (changed to 9090)
    command: server /data --console-address ":9090"  # Custom console address
    networks:
      - dms-network

  worker:
    build: worker/
    container_name: workerContainer
    restart: no
    ports:
      - "8082:8082"
    depends_on:
      - rabbitmq
      - minio
    networks:
      - dms-network


  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.16.0
    container_name: elasticsearch
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
    ports:
      - "9200:9200"
    volumes:
      - elasticsearch-data:/data
    networks:
      - dms-network

  kibana:
    image: docker.elastic.co/kibana/kibana:8.16.0
    container_name: kibana
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    environment:
      - ELASTICSEARCH_URL=http://localhost:9200/
    networks:
      - dms-network

networks:
  dms-network:
    driver: bridge

volumes:
  minio_data:  # Volume for MinIO to store files
  elasticsearch-data:
    driver: local
